### PR TITLE
OKTA-498007: add search parameter to groups endpoint

### PR DESCRIPTION
**Pull request by bryanapellanes-okta**
Adds the `search` parameter to align with documented parameters, see request parameters section of https://developer.okta.com/docs/reference/api/groups/#list-groups

### CODE REVIEW

**Review by arvindkrishnakumar-okta — APPROVED** [review]
lgtm

**Review by monde — APPROVED** [review]
Looks good to me giving the discussion in https://oktainc.atlassian.net/browse/OKTA-498007 and https://oktainc.atlassian.net/browse/OKTA-406629

**Review by laura-rodriguez — COMMENTED** [review]
@bryanapellanes-okta can you please add more details of what we're solving here? Links to the API docs and a draft PR of the .NET SDK might help. Thank you 🙏

**Comment by bryanapellanes-okta** [comment]
> @bryanapellanes-okta can you please add more details of what we're solving here? Links to the API docs and a draft PR of the .NET SDK might help. Thank you 🙏

This change adds back the `search` parameter as described in this JIRA: https://oktainc.atlassian.net/browse/OKTA-498007

**Comment by bryanapellanes-okta** [comment]
Working on draft of regenerated Sdk now, will provide PR link shortly.

**Comment by bryanapellanes-okta** [comment]
@laura-rodriguez draft PR for regenerated dotnet Sdk: https://github.com/okta/okta-sdk-dotnet/pull/552

**Comment by laura-rodriguez** [comment]
Thank you @bryanapellanes-okta! This LGTM. Thinking if we should keep `search` in the same order as before just to avoid a breaking change in the SDK. SDKs can still mitigate it if we decide to continue with this order. I'll let you decide.

**Review by laura-rodriguez — APPROVED** [review]
LGTM

**Comment by bryanapellanes-okta** [comment]
Closing to reopen rebased on current master

**Pull request closed without merging**
