### PR TITLE
Redoc + Github Page

### PR DESCRIPTION
**Pull request by haishengwu-okta**
- I feel this is nice.
https://haishengwu-okta.github.io/okta-management-openapi-spec/

- Given we checked the file, not sure if it's worth to hook with CI atm. Seems ideal approach is CI (bacon) auto push to `gh-pages` branch at every `main` build?

Update Mar 16
- enable travis to auto update gh-pages
- can check details at my fork 
    - deployment history: https://github.com/haishengwu-okta/okta-management-openapi-spec/deployments/activity_log?environment=github-pages
    - travis build: https://travis-ci.com/github/haishengwu-okta/okta-management-openapi-spec/builds

### CODE REVIEW

**Comment by laura-rodriguez** [comment]
Indeed! Looks great ❤️

**Comment by bretterer** [comment]
RE: GH Pages, we can put to gh-pages without bacon.  We do it in other repos (see okta-sdk-php, okta-sdk-java, okta-sdk-python) for samples

This looks awesome!

**Comment by lesterchoi-okta** [comment]
Great start! Just fyi, [the github page](https://haishengwu-okta.github.io/okta-management-openapi-spec/) is public — anyone on internet can view.

I’m looking into how we can render that redoc output in a more functional/contextual (Okta-themed) page (https://github.com/Redocly/redoc#usage-as-a-react-component).

We can look into a [spec linter like Spectral](https://github.com/stoplightio/spectral) to ensure consistency.

I have a recurring discussion with Danni Hu. Some things we should consider...
* i18n + l10n support for the prose
* how to pre-populate some of the example request variables with user-conscious keys/values, e.g., clientId, orgId, if the viewer is signed in.
* delineating API vs SDK
* better search (consider [client-side solution](https://lunrjs.com/) for modularity)

**Comment by arvindkrishnakumar-okta** [comment]
Looks great ❤️

**Review by bretterer — APPROVED** [review]
Woot!... Looks Great!

**Review by laura-rodriguez — APPROVED** [review]
❤️

**Pull request merged**
