### PR TITLE
Fix typo on credentialProvider Enum

### PR DESCRIPTION
**Pull request by alexionescu**
According to https://developer.okta.com/docs/reference/api/system-log/ the schema for

`authenticationContext.authenticationProvider.credentialProvider` should be: `String one of OKTA_CREDENTIAL_PROVIDER, RSA, SYMANTEC, GOOGLE, DUO, YUBIKEY, Optional`

This fixes the typo by renaming the enum value from `OKTA_AUTHENTICATION_PROVIDER` to `OKTA_CREDENTIAL_PROVIDER`

### CODE REVIEW

**Comment by bretterer** [comment]
@alexionescu Thank you for the PR here.  We need to get this in, but to keep with backwards compatibility, I think we should keep the `OKTA_AUTHENTICATION_PROVIDER` as an enum as well.


cc: @laura-rodriguez

**Comment by laura-rodriguez** [comment]
@bretterer I wonder if we should keep the spec with the right type, and then it's up to each SDK to maintain backward compatibility. Thoughts?

**Comment by alexionescu** [comment]
I updated to have both. That seems the safest.

**Comment by alexionescu** [comment]
Somewhat along the same lines...but the generated python client I am using is inconsistent with the actor/target fields as well.

The python client has fields `alternate_id`, `detail_entry`, `display_name`, for the `target` object whereas the documentation & YAML files have it correctly as `alternateId`, `detailEntry`, `displayName`.

The same fields are found in the `actor` object, but the python client there does not have any inconsistencies and it matches up with the docs and YAML spec.

That change will be a bit messy for backwards compatibility if users are relying on the naming of those fields as it will break if renamed, but it's also clunky to keep both fields around tbh.

**Comment by alexionescu** [comment]
No worries!

**Review by bretterer — APPROVED** [review]

**Pull request merged**
