### PR TITLE
Response type for activateNetworkZone and deactivateNetworkZone

### PR DESCRIPTION
**Pull request by sergiishamrai-okta**
This PR solving an inconsistency in `activateNetworkZone` and `deactivateNetworkZone` methods syntax for the `NetworkZone` object in API.
openapi-spec describes the return type for this method as `void` but the actual call returning a `NetworkZone` object.

PR for Java Mgmt SDK: https://github.com/okta/okta-sdk-java/pull/572/files#diff-003145e24599013aff48cf944b56535ef1d263df510788d912f961d256dcbfbaR181-R188

### CODE REVIEW

**Review by bryanapellanes-okta — COMMENTED** [review]
I don't see a problem with this, but I'd like to give @bretterer and @laura-rodriguez a chance to review before merging.

**Comment by sergiishamrai-okta** [comment]
activate/deactivate methods should return void instead of NetworkZone object.
This is a server-side issue.

**Comment by bretterer** [comment]
I don't think this PR needs closed yet.  If the API is returning the object, we need to get info from the team that owns the API to see if it can be documented this way

**Review by serhiibuniak-okta — APPROVED** [review]
LGTM

**Review by laura-rodriguez — APPROVED** [review]
👍

**Pull request merged**
